# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08652b37e69ce48d097f6a731f7879725133c37c17fb8343bb240781e44e5ed49764fc766e79f18139a6b943b553763f987fcf854e736994ef77d36b2bbc6808

test:
  secret_key_base: 462a2453120028f452e48cf77bbaaab0236df8473c882d58b18a1ed1bd5891d247d20d20502a941608cc1b09eefbfeb62fa688ae34e24dec80495bf15634c3fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
